language: php

php:
  - 5.4

script:
  - "wget http://getcomposer.org/composer.phar"
  - php ./composer.phar install
  - "wget http://codeception.com/codecept.phar"
  - php ./codecept.phar build
  - php ./codecept.phar run