language: php

php:
  - 5.4

script:
  - "wget http://codeception.com/codecept.phar"

  - php ./codecept.phar build --config="./tests/codeception.yml"
  - php ./codecept.phar run --config="./tests/codeception.yml"