language: php

php:
  - 5.4

before_script:
  - mysql -e 'create database tests;'

after_success:
  - coveralls

script:
# composer:
  - "wget http://getcomposer.org/composer.phar"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer self-update && composer --version
  - composer global require "fxp/composer-asset-plugin:1.0.0-beta3"
  - composer install
# codecept:
  - "wget http://codeception.com/codecept.phar"
  - php ./codecept.phar build
  - php ./codecept.phar run --coverage --coverage-xml --coverage-html